---
title: "Make 3dLME data table"
output: html_document
---

This script takes first-level FX contrasts (each condition > rest) and age covariates to create the data table input for the 3dLME model.

## load packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
```

## load data
```{r}
# load csv file with fx con file names
#fxCons = data.frame(file = list.files('./data/FX_models/')) # get file names from contrast .nii files
fxCons = read.csv('../../../data/FX_models/fxCons.csv')
  
# print header
fxCons %>%
  head(6) %>%
  kable(format = 'pandoc')

# load age
covariates = read.csv('../../../data/covariates/age.csv')

# print header
covariates %>%
  head(6) %>%
  kable(format = 'pandoc')
```

## tidy data
```{r}
# center age and create quadratic term for age
covariates = covariates %>%
  mutate(age_c = age-13,
         age_c2 = age_c^2) %>%
  select(Subj, wavenum, starts_with("age_c"))

# extract condition information from contrast files
fxCons = fxCons %>%
  extract(file, c("Subj","wavenum","con"), 
          regex = "(s[0-9]{3})_t([0-3]{1})_(con_[0-4]{4}).nii", 
          remove = FALSE) %>%
  mutate(domain = ifelse(con %in% c("con_0001", "con_0003"), "academic", "social"),
         target = ifelse(con %in% c("con_0001", "con_0002"), "self", "other"),
         InputFile = paste0('/Volumes/psych-cog/dsnlab/MDC/functional-workshop/data/FX_models/',file), # CHANGE THIS PATH
         wavenum = as.integer(wavenum))
```

## exclude subjects based on motion and number of timepoints
```{r}
# exclude subjects based on motion
motion.exclusions = c('s002_t1', 's004_t1', 's008_t1', 's011_t1', 's017_t1', 's026_t1', 's033_t2', 's034_t1', 's041_t1', 's044_t1', 's047_t1', 's051_t1', 's054_t1', 's057_t1', 's059_t1', 's061_t1', 's063_t1', 's070_t2', 's074_t1', 's074_t2', 's078_t1', 's084_t1', 's090_t2', 's090_t3', 's094_t1', 's094_t2', 's096_t1')
included.motion = fxCons %>% filter(!grepl(paste(motion.exclusions,collapse="|"), file))

# exclude all subjects that do not have all 3 timepoints
inclusions.3Ts = c('s005', 's016', 's018', 's019', 's022', 's023', 's024', 's029', 's030', 's032', 's035', 's038', 's040', 's042', 's045', 's058', 's064', 's065', 's072', 's073', 's081', 's089')
included.3Ts = fxCons %>% filter(grepl(paste(inclusions.3Ts, collapse="|"), Subj))
```

## merge data
```{r, warning=FALSE, message=FALSE}
age.motion = left_join(included.motion, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, starts_with("age_c"), InputFile) %>%
  filter(!is.na(age_c))

age.3Ts = left_join(included.3Ts, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, starts_with("age_c"), InputFile) %>%
  filter(!is.na(age_c))

# print header
age.motion %>%
  head(10) %>%
  kable(format = 'pandoc')
```

## write files
```{r}
write.table(age.motion, '../../../code/RX_comparison/AFNI/model_all.txt', sep = "\t", quote=FALSE, row.names = FALSE)
write.table(age.3Ts, '../AFNI/model_3Ts.txt', sep = "\t", quote=FALSE, row.names = FALSE)
```
