---
title: "SFIC_models_LME"
output: html_document
---

# load packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

# load data
```{r}
covariates = read.csv('/Volumes/psych-cog/dsnlab/SFIC_data_sheets/SFIC_age.pds.gender.csv')
fxCons = data.frame(file = list.files('/Volumes/psych-cog/dsnlab/SFIC_Self3/analysis/rx/LME_FX/'))
```

# exclude subjects
```{r}
exclusions = c('s002_t1', 's004_t1', 's008_t1', 's011_t1', 's017_t1', 's026_t1', 's033_t2', 's034_t1', 's041_t1', 's044_t1', 's047_t1', 's051_t1', 's054_t1', 's057_t1', 's059_t1', 's061_t1', 's063_t1', 's070_t2', 's074_t1', 's074_t2', 's078_t1', 's084_t1', 's090_t2', 's090_t3', 's094_t1', 's094_t2', 's096_t1')

included = fxCons %>% filter(!grepl(paste(exclusions,collapse="|"), file))
```

# tidy data
```{r}
covariates = covariates %>%
  rename("Subj" = SID,
         "gender" = Gender) %>%
  mutate(Subj = sprintf("s%03d", Subj),
         age_c = age-13,
         age_c2 = age_c^2,
         puberty_c = pds-2.5,
         puberty_c2 = puberty_c^2,
         gender = ifelse(gender == "F", "female",
                  ifelse(gender == "M", "male", NA))) %>%
  select(Subj, wavenum, gender, starts_with("age_c"), starts_with("puberty_c"))

included = included %>%
  extract(file, c("Subj","wavenum","con"), regex = "(s[0-9]{3})_t([0-3]{1})_(con_[0-4]{4}).nii", remove = FALSE) %>%
  mutate(domain = ifelse(con %in% c("con_0001", "con_0003"), "academic", "social"),
         target = ifelse(con %in% c("con_0001", "con_0002"), "self", "other"),
         InputFile = paste0('/projects/dsnlab/SFIC_Self3/analysis/rx/LME_FX/',file),
         wavenum = as.integer(wavenum))
```

# merge data
```{r}
age = left_join(included, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, starts_with("age_c"), InputFile) %>%
  filter(!is.na(age_c))

puberty = left_join(included, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, starts_with("puberty_c"), InputFile) %>%
  filter(!is.na(puberty_c))

age.gender = left_join(included, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, gender, starts_with("age_c"), InputFile) %>%
  filter(!is.na(age_c))

puberty.gender = left_join(included, covariates, by = c("Subj", "wavenum")) %>%
  select(Subj, target, domain, gender, starts_with("puberty_c"), InputFile) %>%
  filter(!is.na(puberty_c))
```

# write files
```{r}
write.table(age, '/Volumes/psych-cog/dsnlab/SFIC_Self3/code/afni/rx/age_exclusions_model.txt', sep = "\t", quote=FALSE, row.names = FALSE)
write.table(puberty, '/Volumes/psych-cog/dsnlab/SFIC_Self3/code/afni/rx/puberty_exclusions_model.txt', sep = "\t", quote=FALSE, row.names = FALSE)

write.table(age.gender, '/Volumes/psych-cog/dsnlab/SFIC_Self3/code/afni/rx/age.gender_exclusions_model.txt', sep = "\t", quote=FALSE, row.names = FALSE)
write.table(puberty.gender, '/Volumes/psych-cog/dsnlab/SFIC_Self3/code/afni/rx/puberty.gender_exclusions_model.txt', sep = "\t", quote=FALSE, row.names = FALSE)
```
